//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int id { get; set; }
        public Nullable<int> valor { get; set; }
        public int idEmpleado { get; set; }
        public int idPregunta { get; set; }
        public int idEvaluacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Eval_Pregunta Eval_Pregunta { get; set; }
    }
}
