//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public Aplicacion()
        {
            this.Rol = new HashSet<Rol>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activa { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
