//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Menu = new HashSet<Menu>();
            this.RolUsuario = new HashSet<RolUsuario>();
        }
    
        public int Id { get; set; }
        public int Aplicacion_Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<RolUsuario> RolUsuario { get; set; }
    }
}
