//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolUsuario
    {
        public int Id { get; set; }
        public int Rol_Id { get; set; }
        public int Usuario_Id { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
