//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.RolUsuario = new HashSet<RolUsuario>();
        }
    
        public int Id { get; set; }
        public int Aplicacion_Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Foto { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public Nullable<System.DateTime> Ultimo_Acceso { get; set; }
        public bool Debe_Cambiar_Password { get; set; }
        public bool Activo { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual ICollection<RolUsuario> RolUsuario { get; set; }
    }
}
